apiVersion: v2
name: sgotel
description: SendGrid Event Webhook to OpenTelemetry publisher
type: application
version: 0.0.2
appVersion: "0.0.2"
icon: https://raw.githubusercontent.com/Tight-Line/sgotel/main/charts/sgotel/icon.png
keywords:
  - sendgrid
  - webhook
  - opentelemetry
  - otel
  - observability
maintainers:
  - name: Tight Line
    email: certs@example.com
