{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sgotel.fullname" . }}-secrets
  labels:
    {{- include "sgotel.labels" . | nindent 4 }}
type: Opaque
stringData:
  SGOTEL_SENDGRID_PUBLIC_KEY: {{ required "sendgridPublicKey is required (or set existingSecret)" .Values.sendgridPublicKey | quote }}
  {{- if .Values.otlp.headers }}
  OTEL_EXPORTER_OTLP_HEADERS: {{ .Values.otlp.headers | quote }}
  {{- end }}
{{- end }}
