sonar.projectKey=Tight-Line_sgotel
sonar.organization=tight-line

sonar.projectName=sgotel
sonar.projectVersion=0.1.0

# Source configuration
sonar.sources=.
sonar.exclusions=**/*_test.go,**/testdata/**,**/vendor/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

# Go coverage report
sonar.go.coverage.reportPaths=coverage.out
sonar.coverage.exclusions=cmd/**/*

# Encoding
sonar.sourceEncoding=UTF-8
